export const CAR_BRANDS = {
    'LiXiang': ["L9","L7","L6","MEGA","I8"],
    'AITO': ["M9","M8","M7","M6"],
    'Zeekr': ["001 2025","001 2026","007","X","007 GT","7X","009","9X"],
    'Voyah': ["Free c 2021","Free c 2023","Free c 2025","Taishan","Dream","Passion","Courage"],
    'BYD': ["ATTO 8","SEAL 6","SEALION 7","YUAN UP","SEAGULL","e2","CHAZOR Champion","SONG PRO DM-i Champion","SONG PLUS EV Champion","HAN"],
    'BMW': ["1-Series","2-Series","3-Series","4-Series","5-Series","6-Series Gran Turismo","7-Series","iX1","iX3","X1","X2","X3","X4","X5","X6","X7"],
    'Chery': ["TIGGO 7PRO","TIGGO 8 PRO-PRO MAX","TIGGO 2 PRO","ARIZZO 6 PRO","ARIZZO 8 HYBRID"],
    'Avatr': ["06","07","11","12"],
    'BAIC': ["BJ 30","BJ 40","BJ 60"],
    'Bestune': ["T55","T99","B70"],
    'BMW M': ["M2","M3","M4","M5","M8","X5M","X6M","X7M","XM"],
    'Cadillac': ["ESCALADE","ESCALADE LONG","ESCALADE V SERIES"],
    'Changan': ["UNI T","UNI K","UNI V","CS 55+"],
    'Chevrolet': ["COBALT MCM","DAMAS","DAMAS MOVE","LABO","ONIX","TRACKER","EQUINOX","TRAVERSE","TRAVERSE Z71","TAHOE RST","TAHOE HIGH COUNTRY","MALIBU XL","CAPTIVA 5"],
    'Deepal': ["S07","G318","SL03","S05","S09"],
    'Dongfeng': ["EP 008","EP 007","AELOUS SHINE GS","NAMMI 06","AELOUS S8 HYBRID","AELOUS L7","SHINE","PALADIN"],
    'Exeed': ["LX","TXL","VX"],
    'Audi': ["RS6","A8L","RSQ8","A7"],
    'GAC': ["AION V","AION S MAX","AION S +","AION Y"],
    'Geely': ["MONJARO","COOLRAY","GALAXY","EX5 EM-I","EX5 EV"],
    'Genesis': ["GV70","G70","GV80","G80","GV80 COUPE","G90"],
    'GWM': ["HAVAL H9","HAVAL H6","HAVAL DARGO","HAVAL JOLION","HAVAL M6","WINGLE 7"],
    'Honda': ["CRIDER","E NS1"],
    'Hongqi': ["EQM 5","HS5","EHS9","H5 REST","H9"],
    'Hyundai': ["SONATA","SANTA FE","TUCSON","ELANTRA","PALISADE","I30","GRANDEUR","STARIA"],
    'Jetour': ["X50","X70","X70 PLUS","X90","X95 PLUS","DASHING","T2","SOUAEST S07","SOUAEST S09"],
    'Kia': ["SONET","SELTOS","SORENTO","SPORTAGE","STINGER","CERARO","CARENS","K5 TURBO","K8","K9","EV6","EV9"],
    'Lexus': ["GX460","LX600","ES 350","IS 250","RX 350","TX500"],
    'Maybach': ["W222","W223","GLS 600"],
    'Mercedes-AMG': ["C63","E63","G63","GT 63","AMG GT","GLE 63","GLS 63","S63","GT43","GT53","C43","E53","G55","SL63","SL55","GLE 53"],
    'Mercedes-Benz': ["C-Class","E-Class","S-Class","GLE","GLC","G-Class"],
    'MG': ["ZS","CYBERSTER","HS","7"],
    'Polestar': ["POLESTAR 2","POLESTAR 4"],
    'Porsche': ["911","MACAN","CAYENNE","PANAMERA","TAYCAN"],
    'Skoda': ["KODIAQ","OCTAVIA","SUPERB"],
    'Tank': ["TANK 300"],
    'Tesla': ["MODEL 3","MODEL Y","MODEL S","MODEL X","MODEL S PLAID"],
    'Toyota': ["LC 120","LC 150","LC 200","LC 300","PRADO 250","CAMRY","AVALON","CROWN","COROLLA","SEQUIOA","RAV 4","HIGHLANDER"],
    'Volkswagen': ["ID 4","ID 6","CADDY","ARTEON","PASSAT SS"],
    'Volvo': ["XC 60","XC 90","T60"],
    'Xiaomi': ["SU 7","SU7 ULTRA","YU 7","YU 7 MAX"],
    'Xpeng': ["XPENG G9","XPENG MONA M03","XPENG P7+","XPENG G3I"],
};
